### ISSUE TITLE
Too swag...

### ISSUE THREAD

**Issue by JWhitmore1** [stackotter/delta-client#1]
This project is **too swag** and wont run on my **unswag** computer

1. run the compiled release
2. too much swag - won't work

Expected behavior: Should run just fine

From terminal run ```/path/to/applications/directory/DeltaClient.app/Contents/MacOS/DeltaClient``` error code 420: too swag

tl;dr, this project is **too swagy** for the average user, pls fix

**Comment by stackotter** [comment]
# TODO: unswag
