### ISSUE TITLE
Can i become a contributor im fontx btw

### ISSUE THREAD

**Issue by iamaleoncoder** [stackotter/delta-client#107]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by stackotter** [comment]
Contributions are made via forking this repository and opening a pull request once you have made the changes you want to make. I don't add people as contributors. Out of interest, what do you want to contribute?

**Comment by iamaleoncoder** [comment]
I want to contribute with making cosmetics and capes and a bit of ideas for the mods

**Comment by Bixilon** [comment]
this is not a minecraft mod.

**Comment by iamaleoncoder** [comment]
> this is not a minecraft mod.
> 
> @stackotter maybe you should pin an issue about the confusion. This issue can be closed and deleted

I know thats fornthe client

**Comment by stackotter** [comment]
currently i am not accepting anything accept for vanilla features in the client, cosmetics and capes should be implemented as a plugin (the plugin system isn't documented, but it would technically be possible to make a plugin that renders cosmetics without changing the plugin system at all).
