### ISSUE TITLE
Make less transparency for the shadows

### ISSUE THREAD

**Issue by iamaleoncoder** [stackotter/delta-client#108]
The transparency for the block shadows looks a bit umm bedrock style and should not go onto that style.

**Comment by stackotter** [comment]
Please fill out the issue description with more details on what you are requesting to be changed

**Comment by stackotter** [comment]
It looks that way because smooth lighting is not yet implemented. The lighting currently looks like Java edition's lighting when smooth lighting is disabled, I don't know if Bedrock allows you disable smooth lighting, but it would look similar.

**Comment by iamaleoncoder** [comment]
> It looks that way because smooth lighting is not yet implemented. The lighting currently looks like Java edition's lighting when smooth lighting is disabled, I don't know if Bedrock allows you disable smooth lighting, but it would look similar.

Thanks
