### ISSUE TITLE
how to start?

### ISSUE THREAD

**Issue by silentspy25** [stackotter/delta-client#118]
cant find any .exe file to start the game can anyone help me here

**Comment by stackotter** [comment]
It’s macOS only at the moment (I assume you’re on windows). You’re probably looking for the PvP client that recently stole our name.

**Comment by silentspy25** [comment]
ah ok thanks and uh i didnt know about that i just googled delta client and got here i thought since it was on gift hub i coudl prolly get it after signing in

**Comment by stackotter** [comment]
yeah, the delta client that stole our name hasn’t released yet, their website is broken and their owner isn’t even in their discord server anymore, so you’re probably better off sticking with lunar or something.

sorry for any confusion the name clash caused though, i really wish they hadn’t stolen the name lol
