### ISSUE TITLE
Render entities before translucent blocks.

### ISSUE THREAD

**Issue by stackotter** [stackotter/delta-client#123]
If you want to start contributing to the renderer, this issue will be a good way to learn your way around the rendering code.

The current render order is:
1. Opaque blocks
2. Translucent blocks
3. Entities
4. GUI

But this doesn't produce the correct result in every case as seen below. The correct order can be obtained by swapping entities and translucent blocks. This will require some refactoring.

<img width="1297" alt="Screen Shot 2022-09-10 at 10 13 36" src="https://user-images.githubusercontent.com/26103979/189460889-aa185dff-dc62-46cf-bd05-c8000146f027.png">

**Comment by gracien-app** [comment]
It's mine.
