### ISSUE TITLE
Notify user when updates are available

### ISSUE THREAD

**Issue by stackotter** [stackotter/delta-client#148]
This issue is a continuation of #16 which @ninjadev64 recently completed. Their PR provides all of the groundwork required for this to be implemented so it should be relatively easy. It's going to be mostly a UI task.

## Overview

Users should be notified when an update is available and the commit they're on is on the main branch (users on commits on non-main branches shouldn't don't need to get notified because otherwise that all starts getting quite a bit more complicated.

The two main options I'm thinking of are either a pop-up on startup (which should be able to be permanently dismissed until the next update), or a button in the sidebar of the main screen that just shows up if an update is available. I'm open to other ideas though.

**Comment by ninjadev64** [comment]
I’ll do this one too

**Comment by ninjadev64** [comment]
I think the "button in the sidebar" approach might be better for now, as it's less intrusive, and users might not want to update so frequently while the client is still under development (plus, saving whether they have dismissed the popup might get messy, especially with seperate installations).

I'll do that first, and then most of the code should be able to be reused if we ever move to the other approach.

**Comment by stackotter** [comment]
> I think the "button in the sidebar" approach might be better for now

I agree
