### ISSUE TITLE
Styled text

### ISSUE THREAD

**Issue by stackotter** [stackotter/delta-client#15]
Minecraft supports two kinds of styled text. A [legacy way that uses a strange unicode character as a delimiter](https://minecraft.fandom.com/wiki/Formatting_codes), and the new way sometimes referred to as [raw json text](https://minecraft.fandom.com/wiki/Raw_JSON_text_format). Currently Delta Client can parse json text and output the text content of it with no styling. Delta Client doesn't support legacy text at the moment (it just outputs it as is with the weird unicode characters and everything).

## Displaying styled text

Delta Client needs to be able to display both kinds of styled text in two ways; as SwiftUI text, and as ansi styled text in the logs (the latter is not quite as important and it's ok if that isn't solved for now).

- [ ] Display json text in SwiftUI
- [x] Parse legacy text
- [x] Display legacy text in SwiftUI
- [x] Update existing UI code to use the new styled text system (solves #14)
- [ ] Display json text as styled ANSI text in terminal
- [ ] Display legacy text as styled ANSI text in terminal

The JSON text parsing system is currently pretty bad and could do with a refactor (which shouldn't take too long anyway because it's not a big system).

**Comment by AlbertoSamele** [comment]
Will do

**Comment by stackotter** [comment]
@AlbertoSamele has implemented all of the parts of this issue that are actually useful at the moment. So I'll close it for now.
