### ISSUE TITLE
I can't bind mouse sidebutton.

### ISSUE THREAD

**Issue by U5KUN** [stackotter/delta-client#167]
**Describe the bug**
I can't bind mouse sidebutton.

**To Reproduce**
1. Go to 'Preferences/Controls'
2. Click on 'keybind change  button'
3. Click mouse sidebutton
4. Mouse sidebutton isn't bound.

**Expected behavior**
It's show me button4 or 5 in keybind.

**Extra information (please complete the following information**
- OS: macOS Sonoma 14.0 Beta
- Hardware: M1 MacBook Pro 13inch 2020
- Build: 582b5e10a2da98ad5a1415356813114f55929689

**Comment by stackotter** [comment]
Thanks for the bug report! When you go back to the game after binding, does clicking the mouse side button do nothing? Or is it just that the name is not what you expected? If the binding doesn’t work, that’s weird, I’ll have to take a look through the input handling code.

The names of the mouse side buttons in code are button 4 and button 5, but I’m happy to change the user-facing names to something more self explanatory if that’s the issue. I’ll check what vanilla Minecraft called them.

**Comment by ninjadev64** [comment]
@stackotter
From what I can tell, the binding isn't working at all. Their issue is not with the names being button 4 and 5 as they listed those as the expected behaviour.

**Comment by stackotter** [comment]
Sorry for the delay, I finally got around to fixing this, it looks like I actually just hadn't implemented support for binding mouse buttons yet. You should be able to bind any mouse button you like with the latest version. Give it a go and let me know if it fixes your issue :)

**Comment by stackotter** [comment]
Download URL for the build: https://github.com/stackotter/delta-client/suites/14809958362/artifacts/842932045
