### ISSUE TITLE
Items rendered incorrectly on inventory branch

### ISSUE THREAD

**Issue by minimcc** [stackotter/delta-client#189]
Non block items (ex: diamonds, sticks, ink sacs. NOT: dirt, stone, stairs etc) are rendered to high when the stack has more than one item. Ex: 1 diamond renders fine but if you have 2 or more diamonds in one stack they are rendered incorrectly. Only happens in the hotbar not in the inventory. 
This does not happen on the main branch

**Comment by stackotter** [comment]
Fixed 👍 Thanks for reporting this issue!
