### ISSUE TITLE
Walking with inventory open

### ISSUE THREAD

**Issue by FloofyPlasma** [stackotter/delta-client#192]
**Describe the bug**
Your character continues to walk with the inventory menu open.

**To Reproduce**
1. Hold a movement key, for example W
2. Open your inventory
3. Observe how your character continues walking

**Expected behavior**
I expect your character to stop walking when you open your inventory.

**Video**
You can find a video displaying this bug [here](https://youtu.be/TJu6kHDYAas).

**Extra information (please complete the following information**
- OS: macOS 14.5 (23F79)
- Hardware: M2 MacBook Air
- Build: Commit [04539f9](https://github.com/stackotter/delta-client/commit/04539f9201257eb06b0789405f0b87182f529b3f)

**Comment by stackotter** [comment]
This should be fixed on the `inventory` branch (which is my current working branch), if not I’ll keep this open

**Comment by stackotter** [comment]
Fixing this now, seems to still be an issue. Affects chat too
