### ISSUE TITLE
Can I be a long-term contributor?

### ISSUE THREAD

**Issue by ninjadev64** [stackotter/delta-client#2]
Unfortunately I cannot help with development because I am clueless with Swift (wouldn’t be able to do something so complex in any language anyway) but I would love to help in any way I can! I’d like to make a website, Discord server, issue templates, bug test etc. And be here for the long term.

**Comment by stackotter** [comment]
feel free to email me at stackotter@stackotter.dev

**Comment by ninjadev64** [comment]
> feel free to email me at [stackotter@stackotter.dev](mailto:stackotter@stackotter.dev)

I've emailed you!
