### ISSUE TITLE
Waterlogged blocks don't render

### ISSUE THREAD

**Issue by thegail** [stackotter/delta-client#21]
**Describe the bug**
Waterlogged blocks do not show water

**To Reproduce**
Open a world and view a waterlogged block. The block renders as it would if it weren't waterlogged.

**Expected behavior**
The block displays as a waterlogged block would in vanilla.

**Screenshots**
![Screen Shot 2021-10-10 at 10 04 02 PM](https://user-images.githubusercontent.com/52760728/136735925-bb2a0935-29b0-4b8c-897f-d42ede4d2561.png)

**Extra information (please complete the following information**
- OS: macOS 11.3.1 Big Sur
- Hardware: 2020 M1 MacBook Air
- Build: Release configuration, branch dev at f49536f463fc78a3c00edaade4cdc5f34e12c386

**Comment by stackotter** [comment]
Hopefully this is easy enough to fix. It was just a complete oversight on my behalf. It also looks like the render order is incorrect.
