### ISSUE TITLE
Add string descriptions for all `LocalizedError`s

### ISSUE THREAD

**Issue by stackotter** [stackotter/delta-client#23]
Currently, the default error description is used which is basically just the enum case printed out. Having more human readable and less *scary* looking descriptions would help regular users troubleshoot a bit better.

**Comment by japanese-goblinn** [comment]
@stackotter Hi! Is this issue still relevant? I'll be happy to help with it

**Comment by stackotter** [comment]
Yep it definitely is! Feel free to [join the Discord server](https://deltaclient.app/discord) so that you can easily ask me for clarification on what certain errors are for if it's not clear :)

**Comment by japanese-goblinn** [comment]
@stackotter Ok, I think that you can assign me on this one and I'll ask you questions if I'll have any 😄

**Comment by stackotter** [comment]
Sounds good, let me know if you need anything 👍
