### ISSUE TITLE
Discord rich presence

### ISSUE THREAD

**Issue by stackotter** [stackotter/delta-client#26]
It'd be nice to have proper Discord integration (Discord rich presence). There is a Swift library for Discord rich presence called [SwordRPC](https://github.com/Azoy/SwordRPC) that should have everything required to add support. Join the Discord and we can chat to decide what statuses should be displayed and so on.

**Comment by AlbertoSamele** [comment]
Catch me on discord when you can, I'll do this

**Comment by stackotter** [comment]
Fixed by @AlbertoSamele in #49
