### ISSUE TITLE
Some things to maybe change in the README

### ISSUE THREAD

**Issue by ninjadev64** [stackotter/delta-client#3]
In the README:

Under Installation, guide users to right click the app and click Open then Open, it’s easier than going into security and privacy settings

Under Troubleshooting, deleting ~/Library/Application Support/DeltaClient/ could also help sometimes

**Comment by stackotter** [comment]
I have fixed the installation guide to use open then open. Thanks for the tip! I didn't know you could do that, it's way easier.

I have updated the Troubleshooting template to be a bit more update and prioritise creating a GitHub issue. And I also updated the Usage section while I was at it to include a small tutorial (three sentences) on running a 1.16.1 server.

**Comment by ninjadev64** [comment]
Nice!
