### ISSUE TITLE
Incorrect color tint

### ISSUE THREAD

**Issue by Matthew15625** [stackotter/delta-client#34]
Grass blocks and leaf blocks have the wrong colour tint.

**Screenshots**
<img width="902" alt="Screenshot 2021-10-27 at 13 15 16" src="https://user-images.githubusercontent.com/43332061/139063976-5e53f4c6-fdd4-43b8-aed9-f769061b5100.png">

**Extra information (please complete the following information**
- OS: macOS 11.6
- Hardware: Intel i7-7700k, Radeon Pro 580
- Build: Version 0.1.0 (9)

**Comment by stackotter** [comment]
Don't know what fixed it, but it just doesn't seem to be happening in the latest build anymore 👍
