### ISSUE TITLE
Still water rendering incorrectly

### ISSUE THREAD

**Issue by Matthew15625** [stackotter/delta-client#35]
**Describe the bug**
Water only renders correctly within a certain radius of the player (also changes with the angle you look at the water, see video below). Beyond that radius it flickers in and out.

**Screenshots**

https://user-images.githubusercontent.com/43332061/139068756-7bdebd89-0815-429e-9f82-bc644c062c28.mp4
(I've had to cut it, speed it up and lower the resolution to get it under 10MB)

**Extra information (please complete the following information**
- OS: macOS 11.6
- Hardware: Intel i7-7700k, Radeon Pro 580
- Build: Version 0.1.0 (9)

**Additional context**
For a frame you can see everything goes black outside the radius where water renders.

**Comment by stackotter** [comment]
Resolved by @gracien. We don't know exactly which of his changes fixed it, but one of them did.
