### ISSUE TITLE
Crash when performing many movement events in a relatively short time. M1 Mac

### ISSUE THREAD

**Issue by JezewskiG** [stackotter/delta-client#36]
Program crashes when too many event inputs are provided in a relatively short amount of time

1. Enter the game
2. Start rapidly providing user control inputs (movement keys) preferably with some double or triple pressing
3. Repeat for some time
4. With four tries, issue happened 3 out of 4 times within a time frame of 3 to 20 seconds

**Expected behavior**
No crash

**Extra information (please complete the following information**
- OS: macOS 12.0.1
- Hardware:  M1 MacBook Air
- Build: commit e4d0459

```
0   DeltaClient                              0x1027e78b0 specialized Set.contains(_:) + 20
1   DeltaClient                              0x1027e75cc Player.updateVelocity() + 188 (Player.swift:172)
2   DeltaClient                              0x1027e75cc Player.updateVelocity() + 188 (Player.swift:172)
3   DeltaClient                              0x10287ff38 RenderCoordinator.updatePhysics() + 92 (RenderCoordinator.swift:116)
4   DeltaClient                              0x10287f6cc RenderCoordinator.draw(in:) + 1000 (RenderCoordinator.swift:77)
5   DeltaClient                              0x10287feb8 @objc RenderCoordinator.draw(in:) + 48
6   MetalKit                                 0x1b68b9ff4 -[MTKView draw] + 288
7   MetalKit                                 0x1b68b9eb4 __23-[MTKView __initCommon]_block_invoke + 48
```

**Comment by stackotter** [comment]
Does this still happen?

**Comment by JezewskiG** [comment]
> 

Happy to say that I was **not** able to reproduce this issue on the latest **dev** build.
