### ISSUE TITLE
Improve launch screen

### ISSUE THREAD

**Issue by stackotter** [stackotter/delta-client#5]
Currently the launch screen is pretty dismal and uninformative. For an example of a SwiftUI progress bar for both downloads and extracting zip see [the code for the in-app updater](https://github.com/stackotter/delta-client/blob/dev/Sources/DeltaClient/Views/Config/UpdateView.swift).

- [x] Add progress bars for downloading and extracting the client jar on first launch
- [x] Make loading messages more detailed and informative for both the first launch and subsequent launches

**Comment by stackotter** [comment]
Maybe even throw in some easter egg loading steps that pop up every so often, such as `frying you an egg` or something. Especially on first launch to entertain peoples' short attention spans.

**Comment by AlbertoSamele** [comment]
Will do
