### ISSUE TITLE
Controls menu doesn't apply changes

### ISSUE THREAD

**Issue by thegail** [stackotter/delta-client#59]
**Describe the bug**
The controls config menu doesn't apply the changes until the player disconnects and rejoins a game.

**To Reproduce**
1. Join server
2. Open in game config menu
3. Change a keybinding
4. Exit the in game settings
5. Observe that the new key bindings have not been applied

**Expected behavior**
The new key bindings should be applied.

**Extra information (please complete the following information**
- OS: macOS 12.0.1
- Hardware: M1 MacBook Air 2020
- Build: 8d1223c80fd9d1efd737a125c1a406eb2c56fb82

**Comment by stackotter** [comment]
Fixed it. It was working properly when hitting escape to exit the in-game menu but not when clicking the button, because I forgot to update the click action and the button was also coded in a weird way which led to that even being possible.
