### ISSUE TITLE
Chunks randomly render black.

### ISSUE THREAD

**Issue by gracien-app** [stackotter/delta-client#69]
Chunks randomly render fully black. It seems that placing a light source in the chunk updates the lighting correctly for nearest blocks, but dark overlay stays the whole time. Happens randomly for all kinds of geometry.

1. Join the game
2. Play for some time, black chunks should start randomly appearing.

**Expected behavior**
No black chunks.

**Screenshots**
<img width="1440" alt="bug" src="https://user-images.githubusercontent.com/56255107/147472785-b8b71a8b-4ca5-4775-a955-d7498247f1fa.png">

**Extra information (please complete the following information**
- OS: macOS 12.1
- Hardware: M1 MacBook Air
- Build: commit 6838c9a052754bebc0218fe2f117218f67087ff4

**Additional context**
Good luck.

**Comment by stackotter** [comment]
Does this still happen for you @JezewskiG ?

**Comment by JezewskiG** [comment]
> Does this still happen for you @JezewskiG ?

Yes, latest dev:
<img width="1012" alt="2022-02-16" src="https://user-images.githubusercontent.com/56255107/154368152-0514884d-7f98-40c6-9664-3b981a889235.png">

**Comment by stackotter** [comment]
Ok, thanks, I guess I just haven't seen it happening recently because I've only been on small worlds.

**Comment by iamaleoncoder** [comment]
Are you Allowed to add opifine settings to your client?

**Comment by stackotter** [comment]
What do you mean by that exactly, and how does that relate to this issue?

Btw, just in case you're wondering, this is not the delta client from the trailer on youtube. That's a different one that annoyingly used the same name

**Comment by stackotter** [comment]
Hopefully this is finally fixed 🤞

**Comment by stackotter** [comment]
It seems to be fixed!

**Comment by gracien-app** [comment]
> It seems to be fixed!

Yay!
