### ISSUE TITLE
invalidGamemode

### ISSUE THREAD

**Issue by ProfRedRooster** [stackotter/delta-client#74]
**Describe the bug**
invalidGamemode when joining a offline server with a offline account
(play.kings-craft.com:25565)

**Expected behavior**
Just join
**Screenshots**
<img width="903" alt="Schermafbeelding 2022-01-01 om 15 09 00" src="https://user-images.githubusercontent.com/52485505/147852453-424f6782-47d6-4717-8a02-c590147d31de.png">

**Extra information (please complete the following information**
- OS: MacOS 12.1
- Hardware: intel Macbook pro 2018
- Build:  6838c9a dev

**Comment by stackotter** [comment]
What gamemode was that server? Was it a survival server? Did it have hardcore enabled?

**Comment by ProfRedRooster** [comment]
Its a bungiechord server with lobby.
The lobby was game mode survival

**Comment by ninjadev64** [comment]
bungeecord*

**Comment by stackotter** [comment]
I think this should be fixed now. Feel free to reopen the issue if it is not.
