### ISSUE TITLE
Fix hang when connecting to the official test server

### ISSUE THREAD

**Issue by stackotter** [stackotter/delta-client#75]
## Steps to reproduce

1. Attempt to connect to the official test server once it has started
2. The entire app hangs and you get a spinning ball of death

## Details

It seems to be a deadlock that occurs when resolving the SRV records, so the server host may have changed how they use SRV records. I think it could possibly be a bug in NioDNS (the library I am using to resolve SRV records), but I would have to look into it further to be sure.

**Comment by stackotter** [comment]
The only version I have produced this on is 6f3b01d (I haven't tried any other versions)

**Comment by ninjadev64** [comment]
The only bug I get when attempting to join the test server is #67

**Comment by stackotter** [comment]
It is possible that it was a DNS issue on my side or a temporary one for the test server. I'll try connecting again tomorrow. Because I am pretty sure that I touched nothing that would break DNS resolution. However, it would probably be a good idea to set a timeout for DNS resolution.

**Comment by stackotter** [comment]
Hasn't ever happened again. I'm gonna close this
