### ISSUE TITLE
Add branch picker to in-app updater

### ISSUE THREAD

**Issue by stackotter** [stackotter/delta-client#8]
Currently, when the 'unstable' update option is chosen, the app is hardcoded to update to the latest successful workflow run from the `dev` branch. It would be nice if users got shown a drop down list and could select which branch to update to. This would be achieved by using the GitHub API.

## GitHub API

[https://api.github.com/repos/stackotter/delta-client/branches](https://api.github.com/repos/stackotter/delta-client/branches) returns a list of all branches on the repo.

The rest of this issue just requires a basic knowledge of SwiftUI to show a dropdown picker in a way that makes it clear that it is for choosing which branch the unstable update will use.

**Comment by ninjadev64** [comment]
my idea :)

**Comment by Matthew15625** [comment]
I'm on it :)

**Comment by stackotter** [comment]
Implemented by @Matthew15625
