### ISSUE TITLE
Legacy formatted text has delimiters in the final text

### ISSUE THREAD

**Issue by stackotter** [stackotter/delta-client#81]
**Describe the bug**
Somehow the delimiters are making it into the NSAttributedString I think

**To Reproduce**
1. Add Hypixel to the server list
2. View the ping result
3. The description is formatted weirdly (see image below)

**Expected behavior**
The text would be formatted correctly

**Screenshots**
<img width="283" alt="Screen Shot 2022-02-04 at 07 50 16" src="https://user-images.githubusercontent.com/26103979/152435704-d6cdb8ef-50fe-449c-b6d9-dcbbb8327a63.png">

The issue doesn't seem to happen for all legacy styled text though, I'm pretty sure the blue text in the image below is also legacy formatted text but it doesn't have the issue:
![Screen_Shot_2022-02-04_at_07 52 26](https://user-images.githubusercontent.com/26103979/152435807-8e0c66d0-d38f-48f2-b56f-e9fa3e1213a1.png)

**Extra information (please complete the following information**
- OS: macOS 12.0.1
- Build: commit 2eb2548

**Comment by AlbertoSamele** [comment]
Will fix this

**Comment by stackotter** [comment]
I rewrote the legacy formatted text implementation to clean it up and it works correctly now
